### ISSUE TITLE
Per Instance Time Limit

### ISSUE THREAD

**Issue by e4stw1nd** [TheAlpha16/isolet#12]
When the instance time limit is once increased to 5 minutes and the time decreases to less than 4 min, it is no longer possible to increase the limit by even a single minute.

**Comment by TheAlpha16** [comment]
As of now, for testing purposes, instances can have a maximum time of 5 min

**Comment by TheAlpha16** [comment]
can you attach a screenshot?

**Comment by TheAlpha16** [comment]
@e4stw1nd
