### ISSUE TITLE
Unique Username

### ISSUE THREAD

**Issue by e4stw1nd** [TheAlpha16/isolet#3]
unique usernames are not enforced

**Comment by TheAlpha16** [comment]
@e4stw1nd usernames are validated before approval. Take a look at 
- goapi/handler/auth.go:68

**Comment by TheAlpha16** [comment]
I just looked at it.
It's not same username exactly but a trailing space at the end

**Comment by TheAlpha16** [comment]
found issues with login input as well

**Comment by TheAlpha16** [comment]
Issue resolved

- Input is now removed of trailing spaces
- inputs are converted to lower case
